# Site settings
title: 尹锋以为
email:  ingf.ivan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Keep It Simple & Stupid Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

paginate: 4

author: inf

gems: [jekyll-paginate]
